name: UwUPunishments
version: ${project.version}
main: uwu.smsgamer.uwup.UwUPunishments
api-version: 1.13
authors: [Sms_Gamer]
description: PUwUnish peOwOple.
website: https://www.spigotmc.org/resources/uwupunishments-actually-tiny.70021/
commands:
  uwupunishments:
    usage: /uwupunishments [command] [arguments...]
    description: Main command.
    aliases:
      - uwup
  punish:
    usage: /punish <player> <reason>
    description: Punish someone.
    aliases:
      - pns
  forgive:
    usage: /forgive <player> <reason>
    description: Forgive someone.
    aliases:
      - frg
  checkviolations:
    usage: /checkviolations <player> <reason>
    description: Checks someone's violations.
    aliases:
      - cvl
      - checkvl
  setviolations:
    usage: /setviolations <player> <reason> <do-action> <amount>
    description: Reloads the plugin.
    aliases:
      - svl
      - setvl
permissions:
  uwu.main.use:
    description: Allows use of the main command.
    default: true
  uwu.punish.use:
    description: Allows to Punish someone.
    default: op
  uwu.forgive.use:
    description: Allows to forgive someone.
    default: op
  uwu.checkvl.use:
    description: Allows to check violations of someone.
    default: op
  uwu.setvl.use:
    description: Allows to set violations of someone.
    default: op
  uwu.pu.exempt:
    description: Prevents other people from affecting you.
    default: op