name: UwUPunishments
author: Sms_Gamer
version: 0.2
main: uwu.smsgamer.uwup.Main
description: PUwUnish ppl.

commands:
   punish:
      usage: /punish <player> <is silent> <reason> [extra]
      description: Main punish command.
      aliases: [pu]
permissions:
   punish.*:
      description: Allows full use of the Punish plugin.
      default: op
      children:
         punish.use: true
         punish.punish: true
   punish.use:
      description: Allows use of the main Punish command.
      default: op
   punish.punish: 
      description: Allows to punish someone.
      default: op