name: UwUPunishments
author: Sms_Gamer
version: 1.2
main: uwu.smsgamer.uwup.Main
description: PUwUnish ppl.
commands:
   punish:
      usage: /punish <player> <broadcast> <reason>
      description: Punish someone.
      aliases:
      - pu
   forgive:
      usage: /forgive <player> <reason>
      description: Forgive someone.
      aliases:
      - fo
   checkviolations:
      usage: /checkviolations <player> <reason>
      description: Checks someone's violations.
      aliases:
      - cv
      - checkvl
   weload:
      usage: /weload
      description: Reloads the plugin.
permissions:
   uwu.punish.use:
      description: Allows to Punish command.
      default: op
   uwu.forgive.use:
      description: Allows to forgive someone.
      default: op
   uwu.pu.reload.use:
      description: Allows to reload the plugin.
      default: op
   uwu.checkvl.use:
      description: Allows to check violations of a person.
      default: op